#if !canImport(ObjectiveC)
import XCTest

extension SPARQLTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SPARQLTests = [
        ("testBasic", testBasic),
        ("testComplex", testComplex),
        ("testFilterGroup", testFilterGroup),
        ("testGroup", testGroup),
        ("testNestedDirectProject", testNestedDirectProject),
        ("testNestedDistinct", testNestedDistinct),
        ("testNestedProject", testNestedProject),
        ("testProjectFilterIsNotHaving", testProjectFilterIsNotHaving),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SPARQLTests.__allTests__SPARQLTests),
    ]
}
#endif
